# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
