# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-25 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_feedbackdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackdata',
            old_name='date',
            new_name='time',
        ),
    ]
